### ISSUE TITLE
Wait for the possibility to get the `redux` name.

### ISSUE THREAD

**Issue by janbaudisch** [redux-rs/redux-rs#1]
I just filed peterbudai/redux#3 to see if we could get access to the `redux` name, we should wait before setting up the repository.

**Comment by jeroenvervaeke** [comment]
That would be nice indeed

**Comment by janbaudisch** [comment]
The author of the `redux` crate did not answer.
I could work on it this weekend, should I simply upload my code as a starting point?

**Comment by jeroenvervaeke** [comment]
Sounds like a good idea.
I'm pretty busy next week but I'm looking forward to work on it.
