### ISSUE TITLE
Create thunk middleware

### ISSUE THREAD

**Issue by jeroenvervaeke** [redux-rs/redux-rs#11]
Since the introduction of 0.2.0 it is possible to write a middleware similar to redux-thunk.
It would be nice to have middleware similar to redux-thunk so we can easily create side-effects.

**Comment by jeroenvervaeke** [comment]
Fixed in PR #12

**Comment by yassinebridi** [comment]
Hey @jeroenvervaeke, is there a reason this is not in the latest version.

Thanks
